// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2024-2026 We-Amp B.V.
//
// llms-generated.test.ts — DRIFT and COVERAGE guard for the agent files.
//
// public/llms.txt and public/llms-full.txt are GENERATED by
// scripts/generate-llms.mjs from the docs collection, the release manifests
// and src/data/product-facts.mjs (plus the prose in src/data/agent-files.mjs);
// public/.well-known/ai-plugin.json from its template and LLMS_TOKENS. The
// same facts also flow into src/pages/api/product.json.ts and
// src/data/offer-jsonld.ts.
//
// This test fails CI whenever:
//   1. BYTE-EQUIVALENCE — a committed file differs from a fresh render (a docs
//      page or a fact changed without `npm run gen:llms`, or a hand edit), or
//      two renders differ (non-determinism).
//   2. TOKENIZED FACTS — the single-sourced license, support, version and
//      heritage facts are missing from the prose.
//   3. NON-TOKENIZED FACTS — vendor, package names and RIDs are missing.
//   4./5. STALE COMMERCIAL COPY — trial, key or per-server pricing language.
//   6. COVERAGE — a published docs page is missing from the index or its full
//      Markdown is missing from llms-full.txt; the sections are not in sidebar
//      order; a distribution channel or package name is missing.
//   7. RETIRED FRAMING — "daemon", a bare "1.16" line label or "ModPageSpeed
//      2.0" as the current product, anywhere outside the archival release-notes
//      entries.
//   8. THE MARKDOWN ROUTE — /docs/<slug>.md serves the same body for every page.

import { readFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { describe, it, expect } from 'vitest';

import {
  generateContent,
  loadContext,
  buildIndex,
  distributionLines,
  PUBLIC_DIR,
  TARGETS,
} from '../../scripts/generate-llms.mjs';
import {
  renderDocMarkdown,
  dockerTag,
  artifactUrl,
  docUrl,
  SITE,
} from '../../src/lib/docs-markdown.mjs';
import { GET as productJsonGet } from '../../src/pages/api/product.json.ts';
import {
  GET as markdownGet,
  getStaticPaths as markdownPaths,
} from '../../src/pages/docs/[slug].md.ts';
import {
  SUPPORT_TIERS,
  SUPPORT_LADDER_MD,
  SUPPORT_LADDER_LINE,
  SUPPORT_URL,
  SOURCE_PUBLICATION,
  LICENSE_CLAUSE,
  LICENSING_TERMS_URL,
  PRICE_VALID_UNTIL,
  MAX_VARIANTS,
  RASTER_VARIANTS,
  PRODUCT_NAME,
  CURRENT_LINE,
  V1_LINE,
  V2_LINE,
  V1_RENUMBERED_FROM,
  COMPANY_FOUNDED_YEAR,
  LAST_UPSTREAM_VERSION,
  SIDECAR_NGINX_VERSION,
  BUILTWITH_SITES,
  BUILTWITH_AS_OF,
  STOCK_NGINX_UBUNTU,
  STOCK_NGINX_ALMA,
  COMPANY_KVK,
  VENDOR,
  COMPANY_COUNTRY,
  PKG_APACHE_MODULE,
  PKG_NGINX_MODULE,
  PKG_OPTIMIZER,
  PKG_ASPNETCORE,
  PKG_SIDECAR,
  PKG_SIDECAR_NATIVE,
  SIDECAR_RIDS,
  ASPNETCORE_RIDS,
  ASPNETCORE_TFMS,
} from '../../src/data/product-facts.mjs';
import { offerJsonLd } from '../../src/data/offer-jsonld.ts';

const generated = generateContent();
const ctx = loadContext();
const index = generated['llms.txt'];
const full = generated['llms-full.txt'];
// The generator's own surfaces: the index (which llms-full.txt opens with) and
// the AI-plugin manifest. The page bodies llms-full.txt embeds are gated at
// their source (src/content/docs/, by content-accuracy.test.ts and
// source-publication-sync.test.ts) and checked for retired framing below.
const combined = [index, generated['.well-known/ai-plugin.json']].join('\n');

// A release-notes page is an archival record: it names past lines and past
// package versions under the names they shipped with. Everything else is
// current copy.
const isReleaseNotes = (slug: string) => /^release-notes(-\d+-\d+)?$/.test(slug);

describe('llms*.txt drift guard', () => {
  describe('1. byte-equivalence: committed file === fresh render', () => {
    for (const { output } of TARGETS) {
      it(`public/${output} is byte-identical to generated output`, () => {
        const committed = readFileSync(resolve(PUBLIC_DIR, output), 'utf8');
        // If this fails, run `npm run gen:llms` (a docs page or a fact changed,
        // or the published file was hand-edited).
        expect(committed).toBe(generated[output]);
      });
    }
    it('a second render is byte-identical (deterministic output)', () => {
      const again = generateContent();
      for (const { output } of TARGETS) expect(again[output]).toBe(generated[output]);
    });
    it('carries no timestamp beyond the manifests’ release dates', () => {
      const allowed = new Set(
        Object.values(ctx.manifests).map((rel) => rel.release.released_on as string),
      );
      const dates = index.match(/\b\d{4}-\d{2}-\d{2}\b/g) ?? [];
      // The release-notes descriptions cite a renumber date; that is content,
      // not a build timestamp.
      const content = ctx.docs.flatMap(
        (d) => d.data.description.match(/\b\d{4}-\d{2}-\d{2}\b/g) ?? [],
      );
      for (const d of dates) expect(allowed.has(d) || content.includes(d), d).toBe(true);
    });
  });

  describe('2. tokenized facts substituted into the prose', () => {
    it('llms.txt carries the license + support + version facts', () => {
      const t = index;
      // The support ladder must appear byte-equivalently as derived from
      // SUPPORT_TIERS — a literalized {{SUPPORT_LADDER_MD}} token or a
      // hand-edited tier row fails here.
      expect(t).toContain(SUPPORT_LADDER_MD);
      expect(t).toContain(LICENSE_CLAUSE);
      expect(t).toContain(SOURCE_PUBLICATION.license);
      expect(t).toContain(LICENSING_TERMS_URL);
      // The retired launch promo must never resurface.
      expect(t).not.toContain('% off year one');
      expect(t).not.toContain('half price');
      expect(t).toContain(`up to ${MAX_VARIANTS} variants per image`);
      expect(t).toContain(`${RASTER_VARIANTS} raster`);
      expect(t).toContain(`${PRODUCT_NAME} ${CURRENT_LINE}`);
      expect(t).toContain(`mod_pagespeed ${V1_LINE}`);
      expect(t).toContain(`renumbered from ${V1_RENUMBERED_FROM}`);
      expect(t).toContain(LAST_UPSTREAM_VERSION);
      expect(t).toContain(BUILTWITH_SITES);
      expect(t).toContain(BUILTWITH_AS_OF);
      expect(t).toContain(COMPANY_KVK);
      expect(t).toContain(`founded ${COMPANY_FOUNDED_YEAR}`);
    });
    it('the Distribution section carries the nginx matrix facts', () => {
      const t = distributionLines(ctx).join('\n');
      expect(t).toContain(`bundles nginx ${SIDECAR_NGINX_VERSION}`);
      expect(t).toContain(STOCK_NGINX_UBUNTU);
      expect(t).toContain(STOCK_NGINX_ALMA);
    });
    it('no unresolved {{TOKEN}} survives into the generated output', () => {
      expect(combined).not.toMatch(/\{\{\s*[A-Za-z0-9_]+\s*\}\}/);
    });
  });

  describe('3. non-tokenized single-sourced facts still appear', () => {
    const literals = [VENDOR, COMPANY_COUNTRY, PKG_ASPNETCORE, PKG_SIDECAR, PKG_SIDECAR_NATIVE];
    for (const lit of literals) {
      it(`"${lit}" appears in llms.txt`, () => {
        expect(index).toContain(lit);
      });
    }
    for (const rid of [...new Set([...SIDECAR_RIDS, ...ASPNETCORE_RIDS])]) {
      it(`RID "${rid}" appears in llms.txt`, () => {
        expect(index).toContain(rid);
      });
    }
  });

  describe('4. no stale commercial copy', () => {
    it('contains no "14-day" / "14 day" trial language', () => {
      expect(combined).not.toMatch(/14[\s-]?day/i);
    });
    it('contains no "stops optimizing" / "stop optimizing" language', () => {
      expect(combined).not.toMatch(/stops? optimizing/i);
    });
    it('contains no trial framing at all', () => {
      expect(combined).not.toMatch(/free trial/i);
    });
    it('never mentions keys, a warn header, or a commercial license for production', () => {
      expect(combined).not.toMatch(/requires a commercial license/i);
      expect(combined).not.toMatch(/license key/i);
      expect(combined).not.toMatch(/X-PageSpeed-Warn/i);
    });
  });

  describe('5. no retired pricing (per-server, and the retired license ladder)', () => {
    it('never prices per server', () => {
      expect(combined).not.toMatch(/server\/month/i);
      // A price per server, or per-server pricing/licensing language. A docs
      // description saying "the response header per server" is not pricing.
      expect(combined).not.toMatch(
        /\$[\d,.]+\s*(?:\/|per)\s*server|per[- ]server (?:pric|licen|fee|cost)/i,
      );
      expect(combined).not.toMatch(/one production server/i);
    });
    it('carries no pre-ladder price points ($49 / $39 / $468)', () => {
      expect(combined).not.toMatch(/\$49(?![\d,.])/);
      expect(combined).not.toMatch(/\$39(?![\d,.])/);
      expect(combined).not.toMatch(/\$468(?![\d,.])/);
    });
    it('carries no license-ladder price points ($99 / $948 / $5,000 as prices)', () => {
      expect(combined).not.toMatch(/\$99(?![\d,.])/);
      expect(combined).not.toMatch(/\$948(?![\d,.])/);
      expect(combined).not.toMatch(/\$5,000(?![\d,.])/);
    });
  });
});

describe('agent files cover the docs collection', () => {
  it('the collection is the one the site builds from (a real page count)', () => {
    expect(ctx.docs.length).toBeGreaterThanOrEqual(40);
    expect(ctx.groups.map((g) => g.label)).toEqual([
      'Start here',
      'Install',
      'Upgrade and migrate',
      'Configure',
      'Filters',
      'Operate',
      'Agents',
      'Reference',
      'Release notes by line',
    ]);
  });

  it('llms.txt opens with the H1 and the one-paragraph summary', () => {
    expect(index.startsWith(`# ${PRODUCT_NAME} ${CURRENT_LINE}\n\n> `)).toBe(true);
    // No heading between the summary and the first link section.
    const beforeFirstSection = index.slice(0, index.indexOf('\n## '));
    expect(beforeFirstSection.split('\n').filter((l) => /^#{2,6} /.test(l))).toEqual([]);
  });

  for (const doc of ctx.docs) {
    it(`llms.txt lists /docs/${doc.slug}/ with its title and description`, () => {
      expect(index).toContain(
        `- [${doc.data.title}](${docUrl(doc.slug)}): ${doc.data.description}`,
      );
    });
    it(`llms-full.txt carries the full Markdown of /docs/${doc.slug}/`, () => {
      const md = renderDocMarkdown(doc, ctx.manifests);
      expect(md.startsWith(`# ${doc.data.title}\n`)).toBe(true);
      expect(full).toContain(md.trimEnd());
    });
  }

  it('each page appears once in the index and once as a body', () => {
    for (const doc of ctx.docs) {
      const url = docUrl(doc.slug);
      expect(index.split(`](${url}): `).length - 1, url).toBe(1);
      expect(full.split(`\nCanonical URL: ${url}\n`).length - 1, url).toBe(1);
    }
  });

  it('the index sections follow the sidebar groups, in order, before the site sections', () => {
    const headings = index
      .split('\n')
      .filter((l) => l.startsWith('## '))
      .map((l) => l.slice(3));
    const groupLabels = ctx.groups.map((g) => g.label);
    expect(headings.slice(0, groupLabels.length)).toEqual(groupLabels);
    expect(headings.slice(groupLabels.length)).toEqual([
      'Tools',
      'Download, pricing and support',
      'Machine-readable',
      'Distribution',
    ]);
    // Inside a group, the pages come in sidebar order.
    for (const group of ctx.groups) {
      const positions = group.docs.map((d) => index.indexOf(`](${docUrl(d.slug)}): `));
      expect(positions, group.label).toEqual([...positions].sort((a, b) => a - b));
    }
  });

  it('llms-full.txt is the index followed by the pages, in sidebar order', () => {
    expect(full.startsWith(buildIndex(ctx).trimEnd())).toBe(true);
    const positions = ctx.docs.map((d) => full.indexOf(`\nCanonical URL: ${docUrl(d.slug)}\n`));
    expect(positions).toEqual([...positions].sort((a, b) => a - b));
  });

  it('every page body has exactly one H1 and absolute links only', () => {
    for (const doc of ctx.docs) {
      const md = renderDocMarkdown(doc, ctx.manifests);
      // Outside fenced code, the title is the only H1.
      let fenced = false;
      const h1s: string[] = [];
      const relative: string[] = [];
      for (const line of md.split('\n')) {
        if (/^(> )?(```|~~~)/.test(line)) {
          fenced = !fenced;
          continue;
        }
        if (fenced) continue;
        if (/^# /.test(line)) h1s.push(line);
        const prose = line.replace(/`[^`]*`/g, '');
        if (/\]\((?:\/|#)/.test(prose)) relative.push(line);
        // No MDX left behind.
        expect(prose, `${doc.slug}: ${line}`).not.toMatch(
          /\{rel\d+\.|<[A-Z][A-Za-z]*\b[^>]*\/>|^import |^export /,
        );
      }
      expect(h1s, doc.slug).toEqual([`# ${doc.data.title}`]);
      expect(relative, doc.slug).toEqual([]);
    }
  });

  it('the Distribution section names every current channel and package', () => {
    const rel21 = ctx.manifests['2.1'];
    const rel20 = ctx.manifests['2.0'];
    const rel11 = ctx.manifests['1.1'];
    const section = index.slice(index.indexOf('\n## Distribution\n'));
    const tag = dockerTag(rel21);
    for (const needle of [
      rel21.urls.archive_base,
      rel21.urls.gpg_key,
      `\`${PKG_APACHE_MODULE}\``,
      `\`${PKG_NGINX_MODULE}\``,
      `\`${PKG_OPTIMIZER}\``,
      `${rel21.artifacts.docker.image}:${tag}`,
      `${rel21.artifacts.docker.worker_image}:${tag}`,
      `\`${rel21.artifacts.helm.chart}\``,
      rel21.artifacts.helm.repository,
      artifactUrl(rel11, 'msi', 'win_x64'),
      `\`${rel20.artifacts.nuget.package}\``,
      `\`${PKG_ASPNETCORE}\``,
      `\`${PKG_SIDECAR}\``,
      `\`${PKG_SIDECAR_NATIVE}\``,
      `${PRODUCT_NAME} ${rel21.release.semver} (${rel21.release.released_on})`,
      rel11.release.tag,
      ...ASPNETCORE_TFMS,
      ...ASPNETCORE_RIDS,
      ...SIDECAR_RIDS,
    ]) {
      expect(section, needle).toContain(needle);
    }
    // Versions come from the manifests, never typed: the docker tag the
    // section carries is the manifest's, and a second pagespeed-* tag is not.
    const tags = [...section.matchAll(/ghcr\.io\/we-amp\/pagespeed-\w+:(\S+?)[`\s)]/g)].map(
      (m) => m[1],
    );
    expect(new Set(tags)).toEqual(new Set([tag]));
  });
});

describe('agent files carry no retired product framing', () => {
  // "daemon" as a name for the worker is retired copy. Literal identifiers that
  // still carry the old word — the admin console's own panel labels, the
  // `daemon.env` file, the `/v1/daemon/` endpoints, `DaemonSocketPath`-style
  // directives, and legacy heading anchors inside URLs — are facts about the
  // product's interfaces, not framing, and are stripped before the check.
  const stripDaemonIdentifiers = (text: string) =>
    text
      .replace(/[\w./:#-]*(?:[_./#-]daemon|daemon[_./-])[\w./:#-]*/gi, '')
      .replace(/\bDaemon\w+/g, '')
      .replace(/\bDaemon\s+(?:Status|Cache|Back-pressure)\b/gi, '')
      .replace(/\bOptimizer daemon\b/g, '');
  // The retired name as the product on offer: a present-tense subject, an
  // install/run imperative, or a heading that is not a migration source
  // ("Migrate from ModPageSpeed 2.0" names where a reader comes from).
  const RETIRED_2_0_AS_CURRENT =
    /\bModPageSpeed 2\.0\s+(?:is|are|runs?|ships?|optimi[sz]es?|supports?|serves?|deploys?|handles?|uses?|generates?)\b|\b(?:[Rr]un|[Ii]nstall|[Dd]eploy|[Tt]ry|[Gg]et|[Uu]pgrade to|[Ss]witch to|[Mm]igrate to|[Cc]hoose)\s+ModPageSpeed 2\.0\b|^#{1,6} (?!.*\bfrom ModPageSpeed 2\.0\b).*ModPageSpeed 2\.0|\bModPageSpeed 2\.1\b|\bMPS ?2\.0\b/m;

  const indexWithoutReleaseNotes = index
    .split('\n')
    .filter(
      (l) => !/\]\(https:\/\/modpagespeed\.com\/docs\/release-notes(?:-\d+-\d+)?\/\): /.test(l),
    )
    .join('\n');

  it('llms.txt (the index) says worker, never daemon', () => {
    expect(stripDaemonIdentifiers(indexWithoutReleaseNotes)).not.toMatch(/\bdaemon\b/i);
  });
  it('llms.txt (the index) carries no "1.16" line label', () => {
    expect(indexWithoutReleaseNotes).not.toMatch(/\b1\.16\b/);
  });
  it('llms.txt (the index) never offers ModPageSpeed 2.0 as the current product', () => {
    expect(indexWithoutReleaseNotes).not.toMatch(RETIRED_2_0_AS_CURRENT);
  });
  it('the generator’s own prose (about + distribution) is clean of all three', () => {
    const own = index.slice(0, index.indexOf('\n## ')) + distributionLines(ctx).join('\n');
    expect(own).not.toMatch(/\bdaemon\b/i);
    expect(own).not.toMatch(/\b1\.16\b/);
    expect(own).not.toMatch(RETIRED_2_0_AS_CURRENT);
  });

  for (const doc of ctx.docs.filter((d) => !isReleaseNotes(d.slug))) {
    it(`/docs/${doc.slug}.md says worker, never daemon, and names no retired line as current`, () => {
      const md = renderDocMarkdown(doc, ctx.manifests);
      expect(stripDaemonIdentifiers(md)).not.toMatch(/\bdaemon\b/i);
      // A past package version ("1.16.0") is a fact; a bare "1.16" line label
      // is the retired framing.
      expect(md).not.toMatch(/\b1\.16\b(?!\.\d)/);
      expect(md).not.toMatch(RETIRED_2_0_AS_CURRENT);
    });
  }
});

describe('/docs/<slug>.md serves the same Markdown', () => {
  it('has a static path for every page and no other', () => {
    const paths = (markdownPaths as () => Array<{ params: { slug: string } }>)();
    expect(paths.map((p) => p.params.slug).sort()).toEqual(ctx.docs.map((d) => d.slug).sort());
  });
  it('responds with text/markdown and the body llms-full.txt carries', async () => {
    const doc = ctx.docs.find((d) => d.slug === 'getting-started')!;
    const res = (markdownGet as (c: unknown) => Response)({
      props: { doc },
      params: { slug: doc.slug },
    });
    expect(res.headers.get('Content-Type')).toBe('text/markdown; charset=utf-8');
    const body = await res.text();
    expect(body).toBe(renderDocMarkdown(doc, ctx.manifests));
    expect(full).toContain(body.trimEnd());
    expect(body.startsWith('# Getting started\n')).toBe(true);
    expect(body).toContain(`Canonical URL: ${SITE}/docs/getting-started/`);
  });
});

describe('ai-plugin.json manifest drift guard', () => {
  // Byte-equivalence + no-unresolved-token + stale-copy sweeps are already
  // covered automatically (the manifest is a TARGET, so it's in the section-1
  // byte loop and in `combined`). These add legible, manifest-specific
  // assertions on the model-facing description.
  const manifest = JSON.parse(generated['.well-known/ai-plugin.json']);

  it('is a valid v1 plugin manifest', () => {
    expect(manifest.schema_version).toBe('v1');
    expect(manifest.name_for_model).toBe('modpagespeed');
  });

  it('description_for_model carries the single-sourced identity + support facts', () => {
    const m: string = manifest.description_for_model;
    expect(m).toContain(`${PRODUCT_NAME} ${CURRENT_LINE}`);
    expect(m).toContain(`mod_pagespeed ${V1_LINE}`);
    expect(m).toContain(`renumbered from ${V1_RENUMBERED_FROM}`);
    expect(m).toContain(LICENSE_CLAUSE);
    // One-line support ladder, byte-equivalent to the derivation from SUPPORT_TIERS.
    expect(m).toContain(SUPPORT_LADDER_LINE);
    expect(m).toContain(LICENSING_TERMS_URL);
    expect(m).toContain(`up to ${MAX_VARIANTS} variants per image`);
  });

  it('does not regress to the stale "14-day free trial" / bare-"1.1" product label', () => {
    const m: string = manifest.description_for_model;
    expect(m).not.toMatch(/14[\s-]?day/i);
    expect(m).not.toMatch(/free trial/i);
    expect(m).not.toContain(`mod_pagespeed ${V1_RENUMBERED_FROM} `);
  });
});

describe('product-facts consumers reflect the single source', () => {
  it('support tiers are placeholder-priced and price-free in their ladder prose', () => {
    for (const t of SUPPORT_TIERS) {
      expect(t.prices.annualUsd).toBeNull();
      expect(t.prices.monthlyUsd).toBeNull();
    }
    expect(SUPPORT_LADDER_MD).not.toMatch(/\$\d/);
    expect(SUPPORT_LADDER_LINE).not.toMatch(/\$\d/);
  });

  it('offer-jsonld emits the $0 Offer', () => {
    const offer = offerJsonLd();
    expect(offer['@type']).toBe('Offer');
    expect(offer.price).toBe(0);
    expect(offer.priceCurrency).toBe('USD');
    expect(offer.priceValidUntil).toBe(PRICE_VALID_UNTIL);
    expect(offer.description).toContain(SOURCE_PUBLICATION.license);
    expect(offer.description).toContain(SUPPORT_URL);
    expect(offer.description).not.toMatch(/commercial license/i);
    expect(offer.description).not.toMatch(/server\/month/i);
  });

  it('/api/product.json reflects the converged identity, support tiers and predecessors', async () => {
    const res = (productJsonGet as (ctx?: unknown) => Response)({});
    const data = JSON.parse(await res.text());
    expect(data.product).toBe(`${PRODUCT_NAME} ${CURRENT_LINE}`);
    expect(data.license).toBe(SOURCE_PUBLICATION.licenseId);
    // The license/publication record is pinned in full by
    // source-publication-sync.test.ts; no evaluation story exists.
    expect(data).not.toHaveProperty('evaluation');
    // Support block mirrors SUPPORT_TIERS (placeholder prices stay null).
    expect(data.support.terms).toBe(LICENSING_TERMS_URL);
    expect(data.support.tiers).toHaveLength(SUPPORT_TIERS.length);
    expect(data.support.tiers.map((t: { id: string }) => t.id)).toEqual(
      SUPPORT_TIERS.map((t) => t.id),
    );
    for (const t of data.support.tiers) {
      expect(t.annual_usd).toBeNull();
      expect(t.monthly_usd).toBeNull();
    }
    // No retired commercial blocks.
    expect(data.pricing).toBeUndefined();
    expect(data.promotion).toBeUndefined();
    expect(data.features.max_variants_per_image).toBe(MAX_VARIANTS);
    // image_formats_by_line keys only grow: predecessors stay, converged joins.
    expect(Object.keys(data.features.image_formats_by_line)).toEqual(
      expect.arrayContaining([V1_LINE, '2.0', CURRENT_LINE]),
    );
    // related_products keeps its key name (public contract). No lifecycle
    // status or date field is served — this is a published endpoint, so it
    // gets the same treatment as llms.txt.
    expect(data.related_products[0].product).toBe(`mod_pagespeed ${V1_LINE}`);
    expect(data.related_products[0]).not.toHaveProperty('status');
    expect(data.related_products[0]).not.toHaveProperty('support_until');
    expect(data.related_products[0].nuget_sidecar.bundled_nginx).toBe(SIDECAR_NGINX_VERSION);
    expect(data.related_products[0].nuget_sidecar.package).toBe(PKG_SIDECAR);
    expect(data.related_products[1].product).toBe(`ModPageSpeed ${V2_LINE}`);
    expect(data.related_products[1]).not.toHaveProperty('status');
    expect(data.related_products[1]).not.toHaveProperty('support_until');
  });
});
