# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024-2026 We-Amp B.V.

"""Pytest fixtures for PageSpeed 2.0 E2E tests.

Manages Docker Compose services as a session-scoped fixture and provides
HTTP clients for nginx and origin servers.
"""

import os
import subprocess
import sys
import time
from dataclasses import dataclass

import pytest
import requests

sys.path.insert(0, os.path.join(os.path.dirname(__file__), ".."))
from common.worker_health import wait_worker_http

E2E_DIR = os.path.dirname(os.path.abspath(__file__))
COMPOSE_FILE = os.path.join(E2E_DIR, "docker-compose.yml")
NGINX_URL = os.environ.get("NGINX_URL", "http://localhost:8083")
ORIGIN_URL = "http://localhost:8082"
WORKER_API_URL = "http://localhost:9881"
# The management API requires a bearer token. Kept in lockstep
# with tools/e2e/entrypoint-worker.sh.
WORKER_API_TOKEN = os.environ.get("PAGESPEED_API_TOKEN", "e2e-harness-test-token")
STARTUP_TIMEOUT = 60  # seconds to wait for services


@dataclass
class ServiceInfo:
    """Addresses of running E2E services."""

    nginx_url: str
    origin_url: str


class PageSpeedClient:
    """HTTP client wrapping requests.Session with PageSpeed helpers."""

    def __init__(self, base_url: str):
        self.base_url = base_url
        self.session = requests.Session()

    def get(self, path: str, headers: dict[str, str] | None = None, **kwargs):
        """GET request to nginx."""
        url = self.base_url + path
        return self.session.get(url, headers=headers or {}, **kwargs)

    def poll_for_hit(
        self,
        path: str,
        timeout: float = 60.0,
        interval: float = 0.5,
        headers: dict[str, str] | None = None,
        expect_smaller_than: int = 0,
    ) -> requests.Response:
        """Poll until X-PageSpeed: HIT is returned, or timeout.

        This accounts for the worker needing time to process the
        notification and write the optimized variant to cache.

        If expect_smaller_than > 0, keeps polling until the response
        body is smaller than this value (to wait for the optimized
        variant rather than accepting the original from cache fallback).
        """
        deadline = time.time() + timeout
        last_response = None
        while time.time() < deadline:
            try:
                resp = self.get(path, headers=headers)
                last_response = resp
                if resp.headers.get("X-PageSpeed") == "HIT":
                    if expect_smaller_than > 0:
                        if len(resp.content) < expect_smaller_than:
                            return resp
                        # HIT but still original size, keep polling
                    else:
                        return resp
            except requests.RequestException:
                pass  # Transient network error, retry
            time.sleep(interval)
        # Return last response even if not a HIT (test can assert on it)
        assert last_response is not None, f"No response received for {path}"
        return last_response

    @staticmethod
    def assert_miss(response: requests.Response):
        """Assert response has X-PageSpeed: MISS header."""
        assert response.headers.get("X-PageSpeed") == "MISS", (
            f"Expected X-PageSpeed: MISS, "
            f"got: {response.headers.get('X-PageSpeed', '<absent>')}"
        )

    @staticmethod
    def assert_hit(response: requests.Response):
        """Assert response has X-PageSpeed: HIT header."""
        assert response.headers.get("X-PageSpeed") == "HIT", (
            f"Expected X-PageSpeed: HIT, "
            f"got: {response.headers.get('X-PageSpeed', '<absent>')}"
        )


def poll_for_variant(
    client: PageSpeedClient,
    path: str,
    headers: dict[str, str] | None = None,
    timeout: float = 20.0,
    interval: float = 0.5,
) -> requests.Response | None:
    """Poll until a HIT with non-empty content is returned.

    Useful for waiting for proactive variants (viewport, density,
    save-data) to be generated by the worker.
    """
    deadline = time.time() + timeout
    last = None
    while time.time() < deadline:
        try:
            r = client.get(path, headers=headers)
            last = r
            if r.headers.get("X-PageSpeed") == "HIT" and len(r.content) > 0:
                return r
        except requests.RequestException:
            pass
        time.sleep(interval)
    return last


def compose_run(*args):
    """Run docker compose command."""
    return subprocess.run(
        ["docker", "compose", "-f", COMPOSE_FILE, *args],
        capture_output=True,
        text=True,
    )


def compose_check(*args):
    """Run docker compose command, raising on failure."""
    return subprocess.run(
        ["docker", "compose", "-f", COMPOSE_FILE, *args],
        capture_output=True,
        text=True,
        check=True,
    )


def docker_exec(service: str, command: str | list[str]) -> subprocess.CompletedProcess:
    """Run a command in a running Docker Compose service container.

    The command can be a simple string (split on whitespace) or a list
    of arguments for commands that contain spaces or special characters.
    """
    if isinstance(command, str):
        cmd_parts = command.split()
    else:
        cmd_parts = command
    return subprocess.run(
        ["docker", "compose", "-f", COMPOSE_FILE, "exec", "-T", service] + cmd_parts,
        capture_output=True,
        text=True,
    )


def _wait_for_nginx(url: str, timeout: float = STARTUP_TIMEOUT):
    """Wait for nginx to respond with a 2xx/3xx status."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            r = requests.get(url + "/", timeout=2)
            if r.status_code < 500:
                return
        except requests.RequestException:
            pass
        time.sleep(1)
    raise TimeoutError(f"Nginx not ready at {url} after {timeout}s")


@pytest.fixture(scope="session")
def e2e_services():
    """Start Docker Compose services, wait for readiness, yield, tear down.

    Set E2E_NO_BUILD=1 to skip the build step (when images are pre-built).
    Set E2E_NO_TEARDOWN=1 to skip the teardown step (keep services running).
    Set E2E_NO_LIFECYCLE=1 to skip all Docker Compose calls (when services
    are managed externally, e.g. by CI workflow steps).
    """
    no_lifecycle = os.environ.get("E2E_NO_LIFECYCLE", "") == "1"
    no_build = no_lifecycle or os.environ.get("E2E_NO_BUILD", "") == "1"
    no_teardown = no_lifecycle or os.environ.get("E2E_NO_TEARDOWN", "") == "1"

    if not no_build:
        # Build images
        compose_check("build")
    if not no_lifecycle:
        # Start all services (idempotent if already running)
        compose_check("up", "-d")
    try:
        # Wait for nginx to be ready
        _wait_for_nginx(NGINX_URL)
        # Wait for the worker API to be responsive and report ready.
        # Delegates to the shared ``wait_worker_http`` helper so every
        # harness fails the same way when the worker never comes up.
        wait_worker_http(WORKER_API_URL, timeout=STARTUP_TIMEOUT)
        yield ServiceInfo(
            nginx_url=NGINX_URL,
            origin_url=ORIGIN_URL,
        )
    finally:
        if not no_teardown:
            # Capture logs for debugging before teardown
            logs = compose_run("logs", "--no-color")
            if logs.stdout:
                print("\n=== Docker Compose Logs ===")
                print(logs.stdout[-3000:] if len(logs.stdout) > 3000 else logs.stdout)
            compose_run("down", "--remove-orphans", "-v")


@pytest.fixture
def client(e2e_services) -> PageSpeedClient:
    """HTTP client pointed at nginx."""
    return PageSpeedClient(e2e_services.nginx_url)


@pytest.fixture
def origin_client(e2e_services) -> requests.Session:
    """HTTP client pointed directly at origin (for baseline comparison)."""
    session = requests.Session()
    session._origin_url = e2e_services.origin_url
    return session


# --- Playwright browser fixtures ---


@pytest.fixture(scope="session")
def playwright_instance():
    """Session-scoped Playwright instance."""
    try:
        from playwright.sync_api import sync_playwright
    except ImportError:
        pytest.skip("playwright not installed")
    with sync_playwright() as p:
        yield p


@pytest.fixture(scope="session")
def chromium(playwright_instance, e2e_services):
    """Session-scoped Chromium browser."""
    browser = playwright_instance.chromium.launch(headless=True)
    yield browser
    browser.close()


@pytest.fixture(scope="session")
def firefox(playwright_instance, e2e_services):
    """Session-scoped Firefox browser."""
    browser = playwright_instance.firefox.launch(headless=True)
    yield browser
    browser.close()


@pytest.fixture(scope="session")
def webkit(playwright_instance, e2e_services):
    """Session-scoped WebKit browser."""
    browser = playwright_instance.webkit.launch(headless=True)
    yield browser
    browser.close()


@pytest.fixture
def page(chromium):
    """Fresh Chromium page per test (isolated context)."""
    context = chromium.new_context()
    p = context.new_page()
    yield p
    context.close()


# --- Configuration test infrastructure ---


class WorkerApiClient:
    """HTTP client for the worker's /v1/* API."""

    def __init__(self, base_url: str, token: str = WORKER_API_TOKEN):
        self.base_url = base_url
        self.session = requests.Session()
        if token:
            self.session.headers["Authorization"] = f"Bearer {token}"

    def get_health(self) -> dict:
        """GET /v1/health and return parsed JSON."""
        r = self.session.get(f"{self.base_url}/v1/health", timeout=5)
        r.raise_for_status()
        return r.json()

    def get_config(self) -> dict:
        """GET /v1/config and return parsed JSON."""
        r = self.session.get(f"{self.base_url}/v1/config", timeout=5)
        r.raise_for_status()
        return r.json()

    def patch_config(self, **kwargs) -> dict:
        """PATCH /v1/config with given fields and return parsed JSON response.

        Returns dict with keys: applied, rejected, warnings, config.
        """
        r = self.session.patch(
            f"{self.base_url}/v1/config",
            json=kwargs,
            headers=self._CSRF_HEADERS,
            timeout=10,
        )
        r.raise_for_status()
        return r.json()

    def patch_config_raw(self, body: str) -> requests.Response:
        """PATCH /v1/config with raw string body (for testing malformed JSON)."""
        return self.session.patch(
            f"{self.base_url}/v1/config",
            data=body,
            headers={"Content-Type": "application/json", **self._CSRF_HEADERS},
            timeout=10,
        )

    def get_stats(self) -> dict:
        """GET /v1/stats and return parsed JSON."""
        r = self.session.get(f"{self.base_url}/v1/stats", timeout=5)
        r.raise_for_status()
        return r.json()

    # CSRF headers required by the worker's mutating endpoints (dual-header check).
    _CSRF_HEADERS = {"X-Requested-With": "XMLHttpRequest"}

    def post_raw(self, path: str, json_body: dict | None = None) -> requests.Response:
        """POST an arbitrary /v1/* path with CSRF headers; returns the raw response.

        Used to assert that removed endpoints answer 404 rather than being
        rejected earlier on CSRF or body grounds.
        """
        return self.session.post(
            f"{self.base_url}{path}",
            json=json_body if json_body is not None else {},
            headers=self._CSRF_HEADERS,
            timeout=10,
        )

    def get_raw(self, path: str) -> requests.Response:
        """GET an arbitrary /v1/* path; returns the raw response."""
        return self.session.get(f"{self.base_url}{path}", timeout=10)


def restart_worker(timeout_sec: float = 30.0):
    """Restart worker container and wait for API readiness."""
    compose_check("restart", "worker")
    deadline = time.time() + timeout_sec
    while time.time() < deadline:
        try:
            r = requests.get(f"{WORKER_API_URL}/v1/health", timeout=2)
            if r.status_code == 200:
                return
        except requests.RequestException:
            pass
        time.sleep(0.5)
    raise TimeoutError(f"Worker API not ready at {WORKER_API_URL} after {timeout_sec}s")


def read_container_file(service: str, path: str) -> str | None:
    """Read a file from inside a running container. Returns None if not found."""
    result = docker_exec(service, ["cat", path])
    if result.returncode != 0:
        return None
    return result.stdout


def stat_container_file(service: str, path: str) -> str | None:
    """Get file permissions (octal) from inside a container. Returns None if not found."""
    result = docker_exec(service, ["stat", "-c", "%a", path])
    if result.returncode != 0:
        return None
    return result.stdout.strip()


def unique_url(base_path: str, test_name: str) -> str:
    """Append unique query string for cache isolation between tests."""
    return f"{base_path}?t={test_name}_{int(time.time() * 1000)}"


# Default config values for auto-restore.
# These match the WorkerConfig defaults in src/worker/worker.h.
DEFAULT_CONFIG = {
    "jpeg_quality": 85,
    "webp_quality": 75,
    "avif_quality": 60,
    "savedata_jpeg_quality": 60,
    "savedata_webp_quality": 50,
    "savedata_avif_quality": 45,
    "content_analysis": True,
    "quality_verify": True,
    "target_ssimulacra2": 70.0,
    "ssimulacra2_tolerance": 5.0,
    "denoise_threshold": 0.3,
    "denoise_sigma_spatial": 3.0,
    "denoise_sigma_range": 25.0,
    "learned_quality": True,
    "learned_quality_jpeg": True,
    "learned_quality_webp": True,
    "learned_quality_avif": True,
    "savedata_score_reduction": 15.0,
    "mobile_width": 480,
    "tablet_width": 768,
    "desktop_width": 0,
    "proactive_image_variants": True,
    "proactive_viewport_variants": True,
    "proactive_savedata_variants": True,
    "proactive_density_variants": True,
    "disable_html": False,
    "disable_lazy_load": False,
    "disable_image_dimensions": False,
    "disable_lcp_preload": False,
    "disable_preconnect_injection": False,
    "enable_speculation_rules": False,
    "disable_css_import_flattening": False,
    "disable_css": False,
    "disable_js": False,
    "disable_image": False,
    "gzip_level": 6,
    "brotli_level": 6,
    "svg_mode": "detect",
    "svg_candidacy_threshold": 50,
    "svg_max_pixels": 65536,
    "svg_color_precision": 0,
    "svg_filter_speckle": 4,
    "svg_max_paths": 500,
    "svg_max_svg_bytes": 262144,
    "svg_exclude_lcp": True,
    "max_url_length": 8192,
    "max_html_size": 5242880,
    "max_css_size": 2097152,
    "max_js_size": 2097152,
    "max_image_size": 10485760,
    "enable_warmup": True,
}


def _wait_for_worker_api(url: str, timeout: float = STARTUP_TIMEOUT):
    """Wait for worker API to respond."""
    deadline = time.time() + timeout
    while time.time() < deadline:
        try:
            r = requests.get(url + "/v1/health", timeout=2)
            if r.status_code < 500:
                return
        except requests.RequestException:
            pass
        time.sleep(1)
    raise TimeoutError(f"Worker API not ready at {url} after {timeout}s")


@pytest.fixture(scope="session")
def worker_api(e2e_services) -> WorkerApiClient:
    """Worker API client (session-scoped, waits for API readiness)."""
    _wait_for_worker_api(WORKER_API_URL)
    return WorkerApiClient(WORKER_API_URL)


@pytest.fixture(autouse=False)
def restore_config(worker_api):
    """Restore config to defaults after a test that modifies it.

    Usage: Add this fixture to tests that PATCH config fields.
    """
    yield worker_api
    try:
        worker_api.patch_config(**DEFAULT_CONFIG)
    except Exception:
        pass  # Best-effort restore; next test suite run starts fresh anyway.
