apiVersion: v1
entries:
  pagespeed:
  - apiVersion: v2
    appVersion: 2.0.36
    created: "2026-07-05T17:27:36.111516+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: ecab22b98796ea6b7d069dbd30cda5ccee1c9c87fc5e05f0beb8f5476f787b1b
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.3.4.tgz
    version: 0.3.4
  - apiVersion: v2
    appVersion: 2.0.35
    created: "2026-07-05T17:27:36.110971+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: ac368628c25507dac3e5251fea3eaf36b08fcc81cd83583706fef98761c95cf8
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.3.3.tgz
    version: 0.3.3
  - apiVersion: v2
    appVersion: 2.0.34
    created: "2026-07-05T17:27:36.110704+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: 690403c9b57fcdf0bfb1b62d8b971edf52037f36b2c4d77effceafba7fbcb2ad
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.3.2.tgz
    version: 0.3.2
  - apiVersion: v2
    appVersion: 2.0.33
    created: "2026-07-05T17:27:36.11044+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: f9f25caa50e0ef6193341fc16138548e00fbd82d2b20f32a5acea7d0bcb58c8e
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.3.1.tgz
    version: 0.3.1
  - apiVersion: v2
    appVersion: 2.0.32
    created: "2026-07-05T17:27:36.110203+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: 4be0643468df5344f05dc863514e90b982fefbbc59292dc93fc9dc9553019500
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.3.0.tgz
    version: 0.3.0
  - apiVersion: v2
    appVersion: 2.0.26
    created: "2026-07-05T17:27:36.109922+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: 5ffef46515691086fb175a05be38d991543a804705992eacb9ed3c7e788b787d
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.2.6.tgz
    version: 0.2.6
  - apiVersion: v2
    appVersion: 2.0.25
    created: "2026-07-05T17:27:36.109665+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: 3880ef5fb5f3d9469946b416ed700b6324056c271170268363f30f2ee87c5e12
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.2.5.tgz
    version: 0.2.5
  - apiVersion: v2
    appVersion: 2.0.24
    created: "2026-07-05T17:27:36.109428+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: 35a5d95dccd237e93984c11a69fb6a52a4bc4bcb2bf85ed506650e2050c43630
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.2.4.tgz
    version: 0.2.4
  - apiVersion: v2
    appVersion: 2.0.23
    created: "2026-07-05T17:27:36.108966+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: 00bfd15b16180263943b2e9fefe4c05a2fe27b2bb08b06ec93b35587de200c53
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.2.3.tgz
    version: 0.2.3
  - apiVersion: v2
    appVersion: 2.0.22
    created: "2026-07-05T17:27:36.107831+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: a7091ee53492d0a2303682339cc28770eb2bbb5890629a037206008428ffa284
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.2.2.tgz
    version: 0.2.2
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2026-07-05T17:27:36.10755+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: dd9b41daceebe78c4583b32f9d34a86fc0716cc697965e47675598e4e55faa84
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.2.1.tgz
    version: 0.2.1
  - apiVersion: v2
    appVersion: 2.0.0
    created: "2026-07-05T17:27:36.107282+02:00"
    description: PageSpeed 2.0 - Nginx image/CSS/JS/HTML optimization
    digest: 5967ea9c58721b8f855c8a7cb55145fe31df7b520b9a906a2578de84a50107c3
    home: https://modpagespeed.com
    keywords:
    - pagespeed
    - nginx
    - optimization
    - webp
    - avif
    - cache
    maintainers:
    - name: we-amp
    name: pagespeed
    sources:
    - https://github.com/oschaaf/modpagespeed-2
    type: application
    urls:
    - https://modpagespeed.com/charts/pagespeed-0.2.0.tgz
    version: 0.2.0
generated: "2026-07-05T17:27:36.106681+02:00"
