#!/usr/bin/env bash
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024-2026 We-Amp B.V.
#
# Generate compile_commands.json for clang-tidy on Linux/Docker CI.
#
# Why this script exists:
#   The Lint job stitches together two bazel invocations + a hedron
#   refresh_all subprocess. The order they run in matters: when refresh_all
#   ran BEFORE the dependent bazel build, the subsequent `bazel build` /
#   `bazel info` invocations (with different effective option-sets than
#   refresh_all's internal aquery subprocess) could discard the analysis
#   cache and, in some workspace states (e.g. when rules_python's venv
#   files have been touched externally between runs), leave the workspace
#   with no usable compile_commands.json — even though hedron had written
#   one moments earlier.
#
#   This script:
#     1. Builds the four genrule targets clang-tidy needs (build_commit.h,
#        html_name_gperf, png, jpeg) FIRST, while the analysis cache is
#        clean.
#     2. Runs `bazel run refresh_all` LAST, with the user's bazel configs
#        propagated to hedron's internal aquery subprocess via the `--`
#        separator, so both layers operate under identical options.
#     3. Validates compile_commands.json exists, is non-empty, is parseable
#        JSON, and contains at least one expected source entry (so a
#        regression that produces an empty/partial file is caught
#        immediately, before clang-tidy's opaque error message buries it).
#
# This script is invoked from inside the pagespeed2-lint Docker container
# by CI. It assumes:
#   - CWD is the workspace root
#   - $BAZEL_REPO_CACHE is set (or defaults to /root/bazel-repo-cache)
#   - $VENDOR_DIR is set (or defaults to "vendor")
#   - SSH key is already wired up (hedron's aquery subprocess fetches
#     the cache library over git+ssh; see the workflow for setup).

set -euo pipefail

BAZEL_REPO_CACHE="${BAZEL_REPO_CACHE:-/root/bazel-repo-cache}"
VENDOR_DIR="${VENDOR_DIR:-vendor}"
WORKSPACE="${BUILD_WORKSPACE_DIRECTORY:-/workspace}"
COMPDB="${WORKSPACE}/compile_commands.json"

# Common bazel arg set used by every invocation in this script.
# Putting them all here keeps the three invocations in lockstep — if the
# outer bazel and the hedron aquery subprocess disagree on options, the
# analysis cache is discarded and hedron may emit "Failed to get action
# keys from Bazel" warnings and an incomplete database.
COMMON_ARGS=(
  --config=docker
  --config=compdb
  --repository_cache="${BAZEL_REPO_CACHE}"
  --vendor_dir="${VENDOR_DIR}"
)

cd "${WORKSPACE}"

# ---------- Step 1: build generated headers first ----------
# clang-tidy needs build_commit.h, product_version_string.h, html_name.gp.h,
# pnglibconf.h, jconfig.h under bazel-bin/. Building these BEFORE refresh_all
# means refresh_all is the last operation that touches bazel state — nothing
# can run after it that might invalidate the analysis cache it just produced.
# product_version_string.h is included by version.h (a very widely-included
# header), so if it's missing clang-tidy fails to parse every dependent TU.
echo "::group::lint-compile-commands: build generated headers"
bazel build \
  "${COMMON_ARGS[@]}" \
  //src/product_version:build_commit \
  //src/product_version:gen_product_version \
  //lib/html:html_name_gperf \
  //lib/image:png \
  //lib/image:jpeg
echo "::endgroup::"

# ---------- Step 2: capture bazel-bin path + ensure build_commit.h ----------
echo "::group::lint-compile-commands: ensure build_commit.h"
BAZEL_BIN=$(bazel info bazel-bin "${COMMON_ARGS[@]}" 2>/dev/null)
if [ -z "${BAZEL_BIN}" ]; then
  echo "::error::bazel info bazel-bin returned empty path"
  exit 1
fi
echo "BAZEL_BIN=${BAZEL_BIN}"

# Fallback: if //src/product_version:build_commit didn't land build_commit.h
# at the expected location (action cache surprises), synthesise it from
# GIT_COMMIT. clang-tidy needs *some* build_commit.h for translation units
# that include it.
if [ ! -f "${BAZEL_BIN}/src/product_version/build_commit.h" ]; then
  mkdir -p "${BAZEL_BIN}/src/product_version"
  COMMIT=$(cat "${WORKSPACE}/GIT_COMMIT" 2>/dev/null | tr -d "[:space:]" || echo "dev")
  SHORT="${COMMIT:0:7}"
  printf '// Generated by gen_build_commit -- do not edit.\n#ifndef PAGESPEED_BUILD_COMMIT_H_\n#define PAGESPEED_BUILD_COMMIT_H_\n\nnamespace pagespeed {\n\ninline constexpr char kBuildCommit[] = "%s";\ninline constexpr char kBuildCommitShort[] = "%s";\n\n}  // namespace pagespeed\n\n#endif  // PAGESPEED_BUILD_COMMIT_H_\n' \
    "${COMMIT}" "${SHORT}" \
    > "${BAZEL_BIN}/src/product_version/build_commit.h"
fi

# Same fallback for product_version_string.h (generated by
# //src/product_version:gen_product_version from VERSION.txt). version.h
# includes it, so every TU that includes version.h needs it present or
# clang-tidy cascades a "file not found" through the whole tree.
if [ ! -f "${BAZEL_BIN}/src/product_version/product_version_string.h" ]; then
  mkdir -p "${BAZEL_BIN}/src/product_version"
  VERSION=$(cat "${WORKSPACE}/VERSION.txt" 2>/dev/null | tr -d "[:space:]" || echo "0.0.0")
  printf '// Generated by gen_product_version -- do not edit.\n#ifndef PAGESPEED_PRODUCT_VERSION_STRING_H_\n#define PAGESPEED_PRODUCT_VERSION_STRING_H_\n\nnamespace pagespeed {\n\ninline constexpr char kProductVersion[] = "%s";\n\n}  // namespace pagespeed\n\n#endif  // PAGESPEED_PRODUCT_VERSION_STRING_H_\n' \
    "${VERSION}" \
    > "${BAZEL_BIN}/src/product_version/product_version_string.h"
fi
echo "::endgroup::"

# ---------- Step 3: refresh_all LAST, propagate flags through `--` ----------
# Without `--`, hedron's internal `bazel aquery` subprocess runs with NO
# configs, which differs from the outer bazel run. Bazel then discards
# the analysis cache and hedron's per-action aquery loop walks a half-
# configured graph, emitting "Failed to get action keys from Bazel" and
# (in some workspace states) producing an incomplete database. The
# `--` separator forwards everything that follows to refresh.py's
# sys.argv[1:], which hedron appends to its aquery args verbatim.
#
# //:refresh_all is the repo-local wrapper (root BUILD) around hedron's
# refresh_compile_commands. It exists because hedron's default
# @hedron_compile_commands//:refresh_all queries deps(//...), and the
# `manual`-tagged fuzz harnesses (//lib/css:css_minify_fuzz,
# //lib/html:html_fuzz) are excluded from that wildcard — their TUs would
# be missing from compile_commands.json, and the lint lane's scoped mode
# would select 0 TUs on a PR touching only such a file, tripping the
# #1094 fail-closed guard.
echo "::group::lint-compile-commands: refresh_all (must be last bazel op)"
# Remove any stale file so a refresh_all that bails before writing leaves
# nothing behind for the guard below to accept.
rm -f "${COMPDB}"
bazel run //:refresh_all \
  "${COMMON_ARGS[@]}" \
  -- \
  --config=docker --config=compdb
echo "::endgroup::"

# ---------- Step 4: validate compile_commands.json ----------
# The four checks below catch four distinct upstream failure modes that
# would otherwise surface as `run-clang-tidy: FileNotFoundError` after
# minutes of misleading clang-tidy output:
#   (a) hedron exited 0 but never wrote the file (rare; see hedron's
#       "Not (over)writing compile_commands.json" log line).
#   (b) hedron wrote an empty file (zero bytes).
#   (c) hedron wrote partial / invalid JSON (e.g. interrupted write).
#   (d) hedron wrote valid JSON but extracted commands for nothing in
#       lib/ or src/ — usually means the aquery subprocess failed and
#       only external/ targets survived. clang-tidy on that DB would
#       lint zero local files and silently pass; CI would never catch
#       a real bug.
echo "::group::lint-compile-commands: validate compile_commands.json"
if [ ! -e "${COMPDB}" ]; then
  echo "::error::compile_commands.json was NOT created at ${COMPDB}"
  echo "diagnostic: any compile_commands.json on disk?"
  find / -name compile_commands.json -size +0c 2>/dev/null | head -20 || true
  exit 1
fi
if [ ! -s "${COMPDB}" ]; then
  echo "::error::compile_commands.json exists but is empty: ${COMPDB}"
  ls -la "${COMPDB}"
  exit 1
fi
echo "compile_commands.json: $(wc -l < "${COMPDB}") lines, $(stat -c%s "${COMPDB}") bytes"

python3 - "${COMPDB}" <<'PY'
import json
import re
import sys
path = sys.argv[1]
with open(path) as f:
    db = json.load(f)
if not isinstance(db, list):
    print(f"::error::compile_commands.json is not a JSON array (got {type(db).__name__})", file=sys.stderr)
    sys.exit(1)
if not db:
    print("::error::compile_commands.json is an empty array (zero entries)", file=sys.stderr)
    sys.exit(1)
# Spot-check that own-source TUs are present, not just external/ ones.
# A regression that wipes own-source entries would otherwise lint nothing.
# Hedron records WORKSPACE-RELATIVE `file` fields (e.g. lib/js/foo.cc), so
# this must be a prefix match; the old '"/lib/" in file' substring test
# never matched an own-source entry and only passed vacuously via
# bazel-out/.../bin/lib/... generated entries (#1094).
own_re = re.compile(r"^(\./)?(lib|src|test)/")
local = [e for e in db if own_re.match(e.get("file", ""))]
if not local:
    print(f"::error::compile_commands.json has {len(db)} entries but none under lib/, src/ or test/", file=sys.stderr)
    print("first 3 entries (for diagnosis):", file=sys.stderr)
    for e in db[:3]:
        print(f"  file={e.get('file')!r}", file=sys.stderr)
    sys.exit(1)
print(f"compile_commands.json: {len(db)} total entries, {len(local)} under lib/, src/ or test/")
PY
echo "::endgroup::"
