#!/usr/bin/env python3

# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2024-2026 We-Amp B.V.

"""
PageSpeed 2.0 — Model Compiler

Converts trained LightGBM models to C source code using TL2cgen,
producing files suitable for inclusion in the Bazel build.

Usage:
    python compile_model.py \
        --model-dir lib/image/generated \
        --output-dir lib/image/generated \
        [--formats jpeg,webp]

Expects {format}_model.txt files from train.py.
Produces {format}_predictor.c and {format}_predictor.h per format.
"""

import argparse
import sys
from pathlib import Path

try:
    import tl2cgen
    import treelite.frontend
except ImportError:
    print(
        "Error: tl2cgen/treelite not installed. Run: pip install tl2cgen",
        file=sys.stderr,
    )
    sys.exit(1)


FEATURE_NAMES = [
    "edge_density",
    "noise_level",
    "unique_color_ratio",
    "photo_metric",
    "color_entropy",
    "spatial_freq_low",
    "spatial_freq_high",
    "mean_luminance",
    "luminance_variance",
    "width",
    "height",
    "content_class",
    "source_format",
    "has_alpha",
    "is_grayscale",
    "target_ssimulacra2",
    "pixel_count",
    "source_quality",
]


def generate_header(fmt: str, n_features: int, output_dir: Path) -> None:
    """Generate a C header with the prediction function declaration."""
    header = f"""\
// Auto-generated by compile_model.py — do not edit.
// LightGBM model compiled to C for {fmt} quality prediction.

#ifndef PAGESPEED_LIB_IMAGE_GENERATED_{fmt.upper()}_PREDICTOR_H_
#define PAGESPEED_LIB_IMAGE_GENERATED_{fmt.upper()}_PREDICTOR_H_

#ifdef __cplusplus
extern "C" {{
#endif

// Predict encoder quality for {fmt} given {n_features} image features.
// features[0..{n_features - 1}] must match the ImageFeatures::ToFloatArray() layout.
// Returns predicted quality as a float (caller should round and clamp).
float predict_{fmt}_quality(const float features[{n_features}]);

#ifdef __cplusplus
}}
#endif

#endif  // PAGESPEED_LIB_IMAGE_GENERATED_{fmt.upper()}_PREDICTOR_H_
"""
    path = output_dir / f"{fmt}_predictor.h"
    path.write_text(header)
    print(f"  Generated header: {path}")


def compile_model(fmt: str, model_dir: Path, output_dir: Path) -> None:
    """Compile a LightGBM model to C source using TL2cgen."""
    import shutil

    model_path = model_dir / f"{fmt}_model.txt"
    if not model_path.exists():
        print(f"  Model not found: {model_path}, skipping.")
        return

    print(f"  Loading model: {model_path}")

    # Load via treelite frontend (tl2cgen 1.0 API).
    tl_model = treelite.frontend.load_lightgbm_model(str(model_path))

    # Derive feature count from the model.
    n_features = tl_model.num_feature
    print(f"  Model expects {n_features} features")

    # Generate C code to temp directory.
    tmp_dir = output_dir / f"_tl2cgen_{fmt}_tmp"
    if tmp_dir.exists():
        shutil.rmtree(str(tmp_dir))
    tmp_dir.mkdir(parents=True)

    tl2cgen.generate_c_code(tl_model, str(tmp_dir), {})

    # Read generated files: header.h and main.c.
    header_file = tmp_dir / "header.h"
    main_file = tmp_dir / "main.c"

    if not main_file.exists():
        # Fallback: search for any .c file.
        for f in tmp_dir.rglob("*.c"):
            main_file = f
            break

    if not main_file.exists():
        print(f"  Error: TL2cgen did not produce a .c file for {fmt}")
        return

    tl2cgen_header = header_file.read_text() if header_file.exists() else ""
    tl2cgen_code = main_file.read_text()

    # Strip the #include "header.h" since we inline the header content.
    tl2cgen_code = tl2cgen_code.replace(
        '#include "header.h"', "// (header.h inlined above)"
    )

    # Extract only the #include and #define lines from the TL2cgen header,
    # skipping forward declarations (which would use unmangled names).
    header_includes = []
    for line in tl2cgen_header.splitlines():
        stripped = line.strip()
        if (
            stripped.startswith("#include")
            or stripped.startswith("#if")
            or stripped.startswith("#else")
            or stripped.startswith("#endif")
            or stripped.startswith("#define")
        ):
            header_includes.append(line)
        elif stripped.startswith("union Entry"):
            # Capture the full union definition.
            header_includes.append(line)
            header_includes.append("  int missing;")
            header_includes.append("  double fvalue;")
            header_includes.append("  int qvalue;")
            header_includes.append("};")

    header_block = "\n".join(header_includes)

    # Write single C file with wrapper that exposes our predict_{fmt}_quality() API.
    # TL2cgen generates: void predict(union Entry* data, int pred_margin, double* result)
    # We wrap it to accept float features[n_features] and return a float.
    wrapper = f"""\
// Auto-generated by compile_model.py — do not edit.
// LightGBM model compiled to C for {fmt} quality prediction.

#include "lib/image/generated/{fmt}_predictor.h"

// ---- Standard includes and types from TL2cgen ----
{header_block}

// Suppress warnings from generated code.
#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wunused-variable"

// Rename TL2cgen symbols to avoid collisions between format predictors.
#define predict predict_{fmt}_internal
#define get_num_target get_num_target_{fmt}
#define get_num_class get_num_class_{fmt}
#define get_num_feature get_num_feature_{fmt}
#define get_threshold_type get_threshold_type_{fmt}
#define get_leaf_output_type get_leaf_output_type_{fmt}
#define postprocess postprocess_{fmt}

// Forward declarations with renamed names.
void predict(union Entry* data, int pred_margin, double* result);
void postprocess(double* result);

// ---- TL2cgen-generated model code ----
{tl2cgen_code}

#pragma clang diagnostic pop

#undef predict
#undef get_num_target
#undef get_num_class
#undef get_num_feature
#undef get_threshold_type
#undef get_leaf_output_type
#undef postprocess

float predict_{fmt}_quality(const float features[{n_features}]) {{
    union Entry data[{n_features}];
    for (int i = 0; i < {n_features}; i++) {{
        data[i].fvalue = (double)features[i];
    }}
    double result = 0.0;
    predict_{fmt}_internal(data, 0, &result);
    return (float)result;
}}
"""
    c_path = output_dir / f"{fmt}_predictor.c"
    c_path.write_text(wrapper)
    print(f"  Generated C source: {c_path}")

    # Clean up temp directory.
    shutil.rmtree(str(tmp_dir), ignore_errors=True)

    # Generate header.
    generate_header(fmt, n_features, output_dir)


def main():
    parser = argparse.ArgumentParser(description="Compile LightGBM models to C")
    parser.add_argument(
        "--model-dir", required=True, help="Directory with *_model.txt files"
    )
    parser.add_argument(
        "--output-dir", required=True, help="Output directory for C files"
    )
    parser.add_argument(
        "--formats", default="jpeg,webp", help="Comma-separated formats"
    )
    args = parser.parse_args()

    model_dir = Path(args.model_dir)
    output_dir = Path(args.output_dir)
    output_dir.mkdir(parents=True, exist_ok=True)

    formats = [f.strip() for f in args.formats.split(",")]

    for fmt in formats:
        print(f"\n=== Compiling {fmt} model ===")
        compile_model(fmt, model_dir, output_dir)

    print("\nDone. Generated C files are ready for Bazel build.")


if __name__ == "__main__":
    main()
